
import 'package:flutter/cupertino.dart';
import 'package:telegram_in/screens/pages_contents_screen.dart';
import 'package:telegram_in/screens/welcome_page.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart' show rootBundle;

class Telegram_tarixi extends StatefulWidget {
  const Telegram_tarixi({Key? key}) : super(key: key);
  static final String id="telegram_tarixi";

  @override
  _Telegram_tarixiState createState() => _Telegram_tarixiState();
}

class _Telegram_tarixiState extends State<Telegram_tarixi> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        backgroundColor: Colors.yellow[200],
        appBar: AppBar(
        backgroundColor: Colors.teal,
        elevation: 0,
          centerTitle: true,
        title:
         Text('Telegram tarixi', style: TextStyle(color: Colors.black,fontWeight: FontWeight.bold,
        fontSize: 18),
    ),
    ),
     // body: Container(child: Image.asset("assets/history.jpg",)),
      body: Stack(
        children: [
          Container(
            height: double.infinity,width: double.infinity,
                color: Colors.teal,
                  child: Image.asset("assets/history.jpg",fit: BoxFit.none,),
              ),
           ListView(
             children: [
               Container(
                 padding: EdgeInsets.only(top: 8,left: 3,right: 3,bottom: 2),
                 child: Text("'Telegram' so'zi Telegramma so`zidan kelib chiqgan."
                     "Telegramma bu axborot yuboruvchi va qabul qiluvchi qurilma."
                     "Telegram Telegrammaning avlodi desa ham bo'ladi."
                     "Telegram asosan smartfonlar uchun mo'jallangan."
                     "Telegram 2013-yil dastlabki versiyasi yaratilgan,bu haqidagi"
                     " ma`lumotlarni keyingi sahifalarimizda o'qishingiz mumkin."
                     "ggggggggggggggggggggggggggggggggr"
                     "grrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrregdfffg"
                     "egggggggggggggggggggggggggggggggggggggggggggg"
                     "gedgerererererererererererererererererererererererererer"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "ererererererererererererererererererererererererer"
                     "ggggggggggggggggggggr"
                     "ggggggggggggggggggggggggggggggggr"
                     "grrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrregdfffg"
                     "egggggggggggggggggggggggggggggggggggggggggggg"
                     "gedgerererererererererererererererererererererererererer"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "ggggggggggggggggggggr"
                     "ggggggggggggggggggggggggggggggggr"
                     "grrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrregdfffg"
                     "egggggggggggggggggggggggggggggggggggggggggggg"
                     "gedgerererererererererererererererererererererererererer"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "ggggggggggggggggggggr"
                     "ggggggggggggggggggggggggggggggggr"
                     "grrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrregdfffg"
                     "egggggggggggggggggggggggggggggggggggggggggggg"
                     "gedgerererererererererererererererererererererererererer"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "ererererererererererererererererererererererererer"
                     "ggggggggggggggggggggr"
                     "ggggggggggggggggggggggggggggggggr"
                     "grrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrregdfffg"
                     "egggggggggggggggggggggggggggggggggggggggggggg"
                     "gedgerererererererererererererererererererererererererer"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "ggggggggggggggggggggr"
                     "ggggggggggggggggggggggggggggggggr"
                     "grrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrregdfffg"
                     "egggggggggggggggggggggggggggggggggggggggggggg"
                     "gedgerererererererererererererererererererererererererer"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "ggggggggggggggggggggr"
                     "ggggggggggggggggggggggggggggggggr"
                     "grrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrregdfffg"
                     "egggggggggggggggggggggggggggggggggggggggggggg"
                     "gedgerererererererererererererererererererererererererer"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "ererererererererererererererererererererererererer"
                     "ggggggggggggggggggggr"
                     "ggggggggggggggggggggggggggggggggr"
                     "grrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrregdfffg"
                     "egggggggggggggggggggggggggggggggggggggggggggg"
                     "gedgerererererererererererererererererererererererererer"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "ggggggggggggggggggggr"
                     "ggggggggggggggggggggggggggggggggr"
                     "grrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrregdfffg"
                     "egggggggggggggggggggggggggggggggggggggggggggg"
                     "gedgerererererererererererererererererererererererererer"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "ggggggggggggggggggggr"
                     "ggggggggggggggggggggggggggggggggr"
                     "grrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrregdfffg"
                     "egggggggggggggggggggggggggggggggggggggggggggg"
                     "gedgerererererererererererererererererererererererererer"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "ererererererererererererererererererererererererer"
                     "ggggggggggggggggggggr"
                     "ggggggggggggggggggggggggggggggggr"
                     "grrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrregdfffg"
                     "egggggggggggggggggggggggggggggggggggggggggggg"
                     "gedgerererererererererererererererererererererererererer"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "ggggggggggggggggggggr"
                     "ggggggggggggggggggggggggggggggggr"
                     "grrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrregdfffg"
                     "egggggggggggggggggggggggggggggggggggggggggggg"
                     "gedgerererererererererererererererererererererererererer"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "ggggggggggggggggggggr"
                     "ggggggggggggggggggggggggggggggggr"
                     "grrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrregdfffg"
                     "egggggggggggggggggggggggggggggggggggggggggggg"
                     "gedgerererererererererererererererererererererererererer"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "ererererererererererererererererererererererererer"
                     "ggggggggggggggggggggr"
                     "ggggggggggggggggggggggggggggggggr"
                     "grrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrregdfffg"
                     "egggggggggggggggggggggggggggggggggggggggggggg"
                     "gedgerererererererererererererererererererererererererer"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "ggggggggggggggggggggr"
                     "ggggggggggggggggggggggggggggggggr"
                     "grrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrregdfffg"
                     "egggggggggggggggggggggggggggggggggggggggggggg"
                     "gedgerererererererererererererererererererererererererer"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "ggggggggggggggggggggr"
                     "ggggggggggggggggggggggggggggggggr"
                     "grrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrregdfffg"
                     "egggggggggggggggggggggggggggggggggggggggggggg"
                     "gedgerererererererererererererererererererererererererer"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "ererererererererererererererererererererererererer"
                     "ggggggggggggggggggggr"
                     "ggggggggggggggggggggggggggggggggr"
                     "grrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrregdfffg"
                     "egggggggggggggggggggggggggggggggggggggggggggg"
                     "gedgerererererererererererererererererererererererererer"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "ggggggggggggggggggggr"
                     "ggggggggggggggggggggggggggggggggr"
                     "grrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrregdfffg"
                     "egggggggggggggggggggggggggggggggggggggggggggg"
                     "gedgerererererererererererererererererererererererererer"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "ggggggggggggggggggggr"
                     "ggggggggggggggggggggggggggggggggr"
                     "grrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrregdfffg"
                     "egggggggggggggggggggggggggggggggggggggggggggg"
                     "gedgerererererererererererererererererererererererererer"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "ererererererererererererererererererererererererer"
                     "ggggggggggggggggggggr"
                     "ggggggggggggggggggggggggggggggggr"
                     "grrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrregdfffg"
                     "egggggggggggggggggggggggggggggggggggggggggggg"
                     "gedgerererererererererererererererererererererererererer"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "ggggggggggggggggggggr"
                     "ggggggggggggggggggggggggggggggggr"
                     "grrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrregdfffg"
                     "egggggggggggggggggggggggggggggggggggggggggggg"
                     "gedgerererererererererererererererererererererererererer"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr""ggggggggggggggggggggr"
                     "ggggggggggggggggggggggggggggggggr"
                     "grrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrregdfffg"
                     "egggggggggggggggggggggggggggggggggggggggggggg"
                     "gedgerererererererererererererererererererererererererer"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "ererererererererererererererererererererererererer"
                     "ggggggggggggggggggggr"
                     "ggggggggggggggggggggggggggggggggr"
                     "grrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrregdfffg"
                     "egggggggggggggggggggggggggggggggggggggggggggg"
                     "gedgerererererererererererererererererererererererererer"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "ggggggggggggggggggggr"
                     "ggggggggggggggggggggggggggggggggr"
                     "grrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrregdfffg"
                     "egggggggggggggggggggggggggggggggggggggggggggg"
                     "gedgerererererererererererererererererererererererererer"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr""ggggggggggggggggggggr"
                     "ggggggggggggggggggggggggggggggggr"
                     "grrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrregdfffg"
                     "egggggggggggggggggggggggggggggggggggggggggggg"
                     "gedgerererererererererererererererererererererererererer"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "ererererererererererererererererererererererererer"
                     "ggggggggggggggggggggr"
                     "ggggggggggggggggggggggggggggggggr"
                     "grrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrregdfffg"
                     "egggggggggggggggggggggggggggggggggggggggggggg"
                     "gedgerererererererererererererererererererererererererer"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "ggggggggggggggggggggr"
                     "ggggggggggggggggggggggggggggggggr"
                     "grrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrregdfffg"
                     "egggggggggggggggggggggggggggggggggggggggggggg"
                     "gedgerererererererererererererererererererererererererer"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr""ggggggggggggggggggggr"
                     "ggggggggggggggggggggggggggggggggr"
                     "grrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrregdfffg"
                     "egggggggggggggggggggggggggggggggggggggggggggg"
                     "gedgerererererererererererererererererererererererererer"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "ererererererererererererererererererererererererer"
                     "ggggggggggggggggggggr"
                     "ggggggggggggggggggggggggggggggggr"
                     "grrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrregdfffg"
                     "egggggggggggggggggggggggggggggggggggggggggggg"
                     "gedgerererererererererererererererererererererererererer"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "ggggggggggggggggggggr"
                     "ggggggggggggggggggggggggggggggggr"
                     "grrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrregdfffg"
                     "egggggggggggggggggggggggggggggggggggggggggggg"
                     "gedgerererererererererererererererererererererererererer"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr""ggggggggggggggggggggr"
                     "ggggggggggggggggggggggggggggggggr"
                     "grrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrregdfffg"
                     "egggggggggggggggggggggggggggggggggggggggggggg"
                     "gedgerererererererererererererererererererererererererer"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "ererererererererererererererererererererererererer"
                     "ggggggggggggggggggggr"
                     "ggggggggggggggggggggggggggggggggr"
                     "grrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrregdfffg"
                     "egggggggggggggggggggggggggggggggggggggggggggg"
                     "gedgerererererererererererererererererererererererererer"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "ggggggggggggggggggggr"
                     "ggggggggggggggggggggggggggggggggr"
                     "grrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrregdfffg"
                     "egggggggggggggggggggggggggggggggggggggggggggg"
                     "gedgerererererererererererererererererererererererererer"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr""ggggggggggggggggggggr"
                     "ggggggggggggggggggggggggggggggggr"
                     "grrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrregdfffg"
                     "egggggggggggggggggggggggggggggggggggggggggggg"
                     "gedgerererererererererererererererererererererererererer"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "ererererererererererererererererererererererererer"
                     "ggggggggggggggggggggr"
                     "ggggggggggggggggggggggggggggggggr"
                     "grrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrregdfffg"
                     "egggggggggggggggggggggggggggggggggggggggggggg"
                     "gedgerererererererererererererererererererererererererer"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "ggggggggggggggggggggr"
                     "ggggggggggggggggggggggggggggggggr"
                     "grrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrregdfffg"
                     "egggggggggggggggggggggggggggggggggggggggggggg"
                     "gedgerererererererererererererererererererererererererer"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     "errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
                     ,style: TextStyle( color: Colors.black54,fontSize: 16),
                   textAlign: TextAlign.justify,

                 ),
               ),
             ],
           ),
        ],
      ),

    );
}
}