class matnlar{
   telegram_tarixi(){
    String text="'Telegram' Telegrammaning zamonaviy va ko'p imkoniyatli ko'rinishi."
        "Telegramma bu axborot yuborishda qo'llaniluvchi vosita."
        "Telegram Telegrammaning avlodi desa ham bo'ladi."
        "Telegram asosan smartfonlar uchun mo'jallangan."
        "Telegram 2013-yil dastlabki versiyasi yaratilgan."
        "2013-yil 14-avgustda dastlabki telegram IOS uchun "
        "paydo bo'ldi.2013-yil 22-avgustda Android platformasi "
        "uchun telegram messangeri yaratildi."
        "shu yilning oktabr oyida messangerining 'telegram.org' "
        "nomli sayti ishga tushdi."
        "2014-yilda birinchi navbatda Telegram har qanday turdagi hujjatlarni, jumladan .pdf, .doc, .png, .mp3 va"
        " hokazolarni yuborishga ruxsat berdi. Har bir fayl uchun o'lcham chegarasi 1,5 GB."
        "Kompyuter uchun norasmiy Telegram ilovasi e`lon qilindi."
        "Android uchun yangi funksiyalar, avtomatik yuklash sozlamalari va kontaktlarni boshqarish vositalari"
    "Ko'proq Telegram ilovalari kurashga kirishdi. Internet uchun norasmiy Telegram ilovasi taqdim etildi va keyinchalik rasmiy"
        " veb-versiyasiga aylanish uchun web.telegram.org saytiga ko‘chirildi. Windows Phone uchun Telegram ilova"
        " ishlab chiqaruvchilar uchun tanlovda yaratilgan."
        "ma'lumotlarga ko'ra 2013-yil noyabr oyi hisobiga ko'ra Telegram "
        "dasturini yuklab olish 1 milliondan oshgan."
        "Telegram 14-sentabrdan boshlab iPad’larni qo‘llab-quvvatlamoqda. Ushbu yangilanishda iOS"
        " ilovasi GIF animatsiyalarini  namoyish etdi va xabarlar uchun bulutli qidiruvni"
        " qo'shdi, shuningdek, Birgalikda hujjatlar bo'limiga fayl nomi bo'yicha qidiruvni qo'shdi."
        " iOS ham Androidni  translyatsiya ro'yxatlarini qo'llab-quvvatladi."
        "2014-yil oktabr Telegram’da to‘g‘ri yozilgan tarixning boshlanishi hisoblanadi."
        " Blog postida tasvirlangan birinchi yangilanish telefon raqamingizni oshkor qilmasdan"
        " Telegram aloqangizni baham ko'rish imkoniyatini qo'shib, ommaviy foydalanuvchi nomlarini"
        " olib keldi. Maxfiy suhbatlar katta yangilanishga ega bo'ldi, o'z-o'zini yo'q"
        " qiladigan media hira eskizlarni ko'rsatadi va ular birinchi ochilgandan keyingina ortga"
        " hisoblashni boshlaydi. Bu ularni ko'rishdan oldin yo'q bo'lib ketishining oldini oldi."
    "Android uchun Telegram bir nechta yangilanishlarga ega bo'lib, Android Wear va planshetlarni"
        " qo'llab-quvvatlash, shuningdek, videoni siqish imkonini berdi."
        "Foydalanuvchi nomiga ega foydalanuvchilarga Telegram’da o‘z profil sahifasini ochadigan"
        " Telegram.me/username havolalari taklif qilindi. Ushbu yangilanish, shuningdek,"
        " Telegram akkauntining telefon raqamini o'zgartirish imkonini berdi. Telegram"
        " ish stoli uchun bitta ustunli rejim qo‘shildi,"
        " bu kichikroq ekranlarda ko‘p vazifalarni bajarishni osonlashtirdi."
        "Telegramning serverlari 5 ta davlatda joylashgan. Yevropa foydalanuvchilari uchun Londondagi "
        "datacenter, Osiyo uchun Singapurdagi datacenter, Amerikaliklar"
        " uchun San - Fransiskodagi va boshqa joydagi datacenterlar bor."
        "Telegramning shtab-kvartirasi Berlinda joylashgan."
        "Datacenterdagi ma`lumotlar bir necha klasterlarda va ma`lum bir kalitlar asosida "
        "shirflangan holda saqlanadi,U ma`lumotlarni copilyatorlarniz "
        "o'qishning imkoni yo'q.Google Durovning Telegram messangerini sotib olmoqchi bo'lgan."
        "Google kompaniyasi vakillari telegramni 1 mlrd dollarga baholashgan."
        "Ushbu holat 2015-yil may oyida bo'lgan."
        "2015-yil sentabr oyida ommaga xabarlarni uzatish uchun mukammal vosita boʻlgan"
        " kanallar keltirildi. Kanallar cheksiz obunachilarga ega bo'lishi mumkin, har"
        " bir post uchun ko'rish hisoblagichlarini taklif qilishi va faqat administratorlarga"
        " xabar yuborishiga ruxsat berishi mumkin. Ushbu bir tomonlama suhbatlar muhokamani boshqa"
        " joyga ko'chirish orqali yangilanishlarga diqqat markazida bo'ladi."
        "2016-yil aprel oyidan boshlab, inline botlar endi klaviaturadan foydalanishni"
        " talab qilmaydi. Ushbu dasturiy ta'minot tomonidan boshqariladigan do'stlar endi"
        " hech qanday yozishni talab qilmasdan natijalarga erishish uchun darhol bosiladigan"
        " variantlarni taqdim etadilar. Ular, shuningdek, oson video va joylashuvni"
        " almashish uchun YouTube va Foursquare kabi xizmatlar bilan birlashtirilgan.";
    return text;
  }
  telegram_asoschisi(){
     String text="Pavel Durov 1984-yil 10-oktabr Rossiyaning Sankt-Peterburg shahrida tavallud topgan."
         "Pavel 11-yoshidan boshlab dasturlashga qiziqadi va o'rganishni boshlaydi."
         "2006-yilda Pavel  Sank Peterburg davlat universitetinining filiollogiya "
         "fakultetini tamomlaydi. Universitetda o'qish mobaynida harbiy fakultetni ham tamomlab"
         " zahiradagi leytenant unvoniga erishadi,"
         " U universitetni qizil diplomga tamomlab,o'sha yili Vkontakt ijtimoiy tarmog`ini yaratadi."
         "2012-yil 19-noyabrda 'Mann,Ivanov va Ferber' nashiryoti Nikolay Kanonovaning' Kod Durova'deb nomlangan kitobni "
         "chiqardi.Bu kitobda Pavel Durov intervyulardagi nutqlari asosida yozilgan."
         "\n Pavel Durovning boylik haqida nutqlari\n"
         "Mening hayot tarzimni koshonalarda, qo'sha-qo'sha mashinalarda va shaxsiy samalyotlarda "
         "tasavvur qilgan odamlar qattiq yanglishadilar. Menda na samalyot na qimmat sport mashinalari yoki hashamatli saroy bor"
         "Mening kundalik turmushim nihoyatda sodda.Ishga metroda qatnayman va samarali ishdan so'ng 18-20 metr-kvadrat maydondagi "
         "ijara uyda umrguzaronlik qilish."
         "Ma'lumki, 2011 yil dekabr oyida FSB Pavel Durovga beshta jamoa va ikkita uchrashuvni bloklashni taklif qilgan."
         " Durov bundan bosh tortdi. Shundan so'ng uni Sankt-Peterburg prokuraturasiga tushuntirishlar berish uchun chaqiruv qog'ozi  jo'natishdi."
         "VKontakteda ishlayotganda, Pavel ofis yaqinidagi ijaraga olingan kvartirada yashagan."
         "2014 yil fevral oyida VKontaktening 48% ulushiga ega bo'lgan United Capital Partners Fund (UCP) Rossiya"
         " va xalqaro yurisdiksiyalarda o'z manfaatlarini himoya qilish niyatida ekanligini e'lon qildi."
         " UCP vakillari Pavel Durov va Mail.ru Group xodimlarini VK manfaatlariga zid harakatlarda "
         "aybladilar. Jamg'armaning tushuntirishicha, ular ilgari muammolarni tinch yo'l bilan hal"
         " qilishga harakat qilishgan, ammo barcha takliflar o'sha paytda VK ning nazorati ostida (52%)"
         " bo'lgan Mail.ru Group vakillari va Megafon bosh direktori Ivan Tavrin tomonidan bloklangan."
         " UCP ta'kidlashicha, VK mualliflarining bunday xatti-harakatlari ularni juda ajablantiradi va"
         " xavotirga soladi. Oqilona kelishuvga erishish uchun barcha imkoniyatlarni ishga solib,"
         "quyidagi so'zlarni aytgan: biz VKdagi bahsli ishlarni advokatlik firmalariga topshiramiz."
    "UCP hamkori Yuriy Kachuro, bunga javoban USM Advisors bosh direktori Ivan Streshinskiy"
         " UCPni VK aktsiyadorlariga tizimli bosim o'tkazishda aybladi: VKontakte-ga e'lon"
         " qilinganidan beri UCP boshqa aktsiyadorlar va kompaniya rahbariyati bilan konstruktiv munosabatlar o'rnatishni istamadi."
    "VKontakte - Runetdagi eng yirik ijtimoiy tarmoq, 2012 yilda Belarusda birinchi, Rossiyada ikkinchi,"
         " Ukrainada uchinchi, Qozog'istonda beshinchi, dunyoda 26-o'rinda, 1,5 milliard dollarga baholangan. Misol"
         " uchun, 2012 yil sentyabr oyida saytning kunlik auditoriyasi o'rtacha 22 million kishini tashkil etgan."
         " O'sha yilning sentyabr oyi holatiga ko'ra, VKontakte-da 140 milliondan ortiq foydalanuvchi ro'yxatdan o'tgan.";
     return text;
  }
  telegram_turlari(){
    // "Telegram turlarini quyida keltirib o'tamiz."
    //     "Telegram x ,Telegraph, Momogram , Turbogram , Videogram , Plus  va boshqalar.\n\n"
     String text=
         "Telegraph - anonim bloglar platformasi, Telegram tomonidan yaratilgan bepul nashr qilish vositasi."
         " Telegraph asosan Telegram messenjerida uzun matnlarni almashish vositasi sifatida yaratilgan bo‘lsa-da,"
         " Telegram akkauntisiz foydalanish mumkin bo‘lgan mutlaqo alohida xizmatdir."
     "Platforma 2016-yilning 22-noyabrida Telegram’ning 3.14 versiyasi chiqarilishi bilan bir vaqtda e’lon qilingan edi."
         "Telegrafiya - bu xabarlarni uzoq masofaga uzatish, bunda jo'natuvchi xabarni olib"
         " yuruvchi ob'ektni jismoniy almashinuvi emas, balki qabul qiluvchiga ma'lum bo'lgan ramziy"
         " kodlardan foydalanadi. Shunday qilib, bayroq semafori telegraf usulidir, kaptar posti esa bunday emas."
         " Qadimgi signalizatsiya tizimlari, ba'zan Xitoydagi kabi juda keng va murakkab bo'lsa ham, odatda o'zboshimchalik"
         " bilan matnli xabarlarni uzatishga qodir emas edi. Mumkin bo'lgan xabarlar aniqlangan va oldindan belgilangan va shuning"
         " uchun bunday tizimlar haqiqiy telegraf emas.Telegraph(o'zbek tilida o'qilishi  telegraf)."
     "Keng qo'llanilgan eng birinchi haqiqiy telegraf XVIII asr oxirida ixtiro qilingan Klod Chappening optik telegrafi bo'ldi."
         " Tizim Frantsiyada va Fransiya tomonidan bosib olingan Yevropa xalqlarida, Napoleon davrida keng qo'llanilgan. Elektr "
         "telegrafi 19-asr oʻrtalarida optik telegraf oʻrnini bosa boshladi. U birinchi marta Britaniyada Kuk va Uitstoun telegrafi"
         " shaklida qo'llanilgan va dastlab temir yo'l signalizatsiyasiga yordam sifatida ishlatilgan. Bu tezda Amerika Qo'shma Shtatlarida"
         " Samuel Morse tomonidan ishlab chiqilgan boshqa tizim tomonidan ta'qib qilindi. O'rnatilgan optik telegraf tizimi tufayli elektr telegraf"
         " Frantsiyada sekinroq rivojlandi, lekin elektr telegraf Chappe optik telegrafiga mos keladigan kod bilan foydalanishga topshirildi. Morze"
         " tizimi 1865 yilda xalqaro standart sifatida 1848 yilda Germaniyada ishlab chiqilgan o'zgartirilgan Morze kodidan foydalangan holda qabul qilingan."
    "Geliograf - bu signal berish uchun quyosh nurlarining aks ettirilishidan foydalanadigan telegraf tizimi. U asosan elektr telegrafi o'rnatilmagan hududlarda"
         " ishlatilgan va odatda bir xil koddan foydalanilgan. Eng keng tarqalgan geliograf tarmog'i Apache urushi paytida Arizona va Nyu-Meksikoda tashkil etilgan."
         " Geliograf Ikkinchi Jahon urushi davridayoq standart harbiy texnika edi. Simsiz telegraf 20-asr boshlarida rivojlangan. Simsiz telegraf dengizda foydalanish"
         " uchun muhim ahamiyatga ega bo'ldi va xalqaro aloqada suv osti telegraf kabellaridan foydalangan holda elektr telegrafiga raqobatchi bo'ldi."
    "Telegramma narxlari yetarlicha tushib ketganidan so'ng, telegrammalar xabarlarni jo'natishning mashhur vositasiga aylandi. Avtomatlashtirilgan tizimlar - teleprinterlar"
         " va zarbli lenta uzatishning rivojlanishiga turtki bo'lish uchun trafik etarlicha yuqori bo'ldi. Bu tizimlar Bodo kodidan boshlab yangi telegraf kodlarini keltirib chiqardi."
         " Biroq, telegrammalar hech qachon narx bo'yicha xat pochtasi bilan raqobatlasha olmadi va ularning tezligi ustunligini yo'qotgan telefon raqobati 1920 yildan boshlab telegrafni"
         " tanazzulga olib keldi. Qolgan bir nechta telegraf ilovalari asosan 20-asrning oxirlarida Internetdagi muqobil dasturlar tomonidan qabul qilingan.\n"
         "Quyida 2018 yil 31 yanvar"
     "Telegram jamoasi  tomonidan yozilgan:"
     "Telegram X-ning maqsadi - Telegram-ni qayta ixtiro qilish va tezlik, foydalanish qulayligi, animatsiya sifati va boshqa barcha jihatlar bo'yicha yangi"
         " chegaralarni o'rganishdir.ikkita yangi rasmiy ilovani – Android va iOS uchun Telegram X-ni taqdim etilgan."
    "Bu ikkala ilova ham eksperimental boʻlib, mavjud rasmiy ilovalarning oʻrnini egallashi yoki boʻlmasligi mumkin. Ammo ular buni qilmasa ham,"
         " yangi yondashuv va texnologiyalarni tezda sinab ko‘rish imkonini berib, Telegram’ning rivojlanishini tezlashtiradi."
    "Android uchun Telegram X ikki yil avval asoschimiz boshlagan Android dasturchilari uchun tanlov o'choqlarida tug'ildi. Keyin g'olib TDLib"
         " kuchidan foydalanib, silliq animatsiyalarga alohida e'tibor qaratgan ajoyib ilovani yaratdi."
    "Android uchun X original ilovaga qaraganda tezroq va batareya quvvatini tejaydi va zamonaviy yangi dizaynga ega."
    "Telegram X da istalgan chatni ochmasdan turib uning mazmunini ko‘rish uchun uni bosib turishingiz mumkin. Bu hamma joyda ishlaydi, jumladan,"
         " yo'naltirish va almashish menyularida, shuningdek, Qo'ng'iroqlar va 'Umumiy guruhlar' yorlig'ida."
    "Ilova, shuningdek, ko'plab foydali surish harakatlarini taklif etadi. Masalan, asosiy ekranda chapga va o‘ngga surish orqali “Chatlar” va"
         " “Qo‘ng‘iroqlar” o‘rtasida almashishingiz mumkin. Yo‘naltirish menyusini darhol ochish uchun istalgan xabarni o‘ngga surishingiz mumkin."
    "Ilovada qayta ishlangan musiqa pleyeri va biriktirma menyusi, shuningdek umumiy mediaga tezkor kirish imkoniga ega optimallashtirilgan profil"
         " sahifalari mavjud. Surish orqali turli xil umumiy media turlarini osongina almashtirishingiz mumkin."
    "Bu funksiyalarning to‘liq ro‘yxati emas, Android uchun Telegram X har bir burchakda kichik syurprizlarga to‘la."
    "IOS uchun X 2018-yil oktabr oyidan boshlab iOS uchun Telegram X eski Objective-C asosidagi mijozni almashtirdi."
    "iOS uchun Telegram X butunlay Swift-da yozilgan va Objective C bilan yaratilgan asl ilovaga qaraganda ancha engilroq, tezroq va batareya quvvatini tejaydi."
    "Dizayn va funksiyalar to‘plami iOS foydalanuvchilari Telegram’dan kutishni o‘rgangan narsaga yaqinroqdir, lekin ko‘pchilik iPhone’larda silliq"
         " animatsiyalar va tezroq tezlik va yuklash vaqtlarini albatta sezasiz."
    "iOS uchun Telegram X ichki tuzilishi ham 2018 va undan keyingi yillarda Telegram ilovasidan kutilayotgan narsalar uchun ancha yaxshi optimallashtirilgan."
         " Xuddi Android uchun X bilan bo'lgani kabi, iOS uchun bugungi X versiyasi ham uzoq sayohatning boshlanishidir.";
     return text;
  }
  telegram_versiyalari(){
     String text=""
         "2013-yil oktyabr oydagi telegramning yangilangan versiyasidagi qo'shilgan imkoniyatlar,"
         "Android dasturchilari uchun tanlovdan so'ng Android uchun Telegramning alfa versiyasiishga tushirilgan"
         "telegram habarlarni o'chirish vaqti va maxfiy suhbatlar qo'shilgan."
         "2014-yil yanvar oyidagi versiyasida telegram har qanday turdagi hujjatlarni , jumladan .pdf,.doc,.mp3 va boshqa "
         "formatdagi fayllarni yuborishga ruxsat berilgan, ularning maksimal hajmi 1,5 gigabayt."
         "Kompyuter uchun norasmiy Telegram ilovasi e'lon qilindi,ya'ni birinchi versiyasi ishlab chiqildi, "
         "2014-yil iyun oyidagi bo'lgan yangilanishlar Android uchun foydalanuvchilarga suratlarni"
         "jo'natishdan oldin ko'rish,shuningdek , bir vaqtning o'zida bir nechta fotosuratlarni tanlash va yuborish"
         "imkoniyatlari qo'shildi va bildirnomalarni yaxshilandi.2014-yil dekabr oyidagi  yangilanishlar , foydalanuvchi"
         "nomiga ega foydalanuvchilarga Telegramda o'z profil sahifasi ochadigan Telegram.me/username  havolalari"
         "taklif qilindi. Ushbu yangilanish , shuningdek , Telegram akkauntining telefon raqamini o'zgartirish imkonnini"
         "berilgan. Telegram 2015-yil yanvar oyidagi versiyasida birinchi stiker paydo bo'ldi, birinchi stikerlar to'plami"
         "klassik 'Great Minds' to'plamini tashkil etdi va suratlarni bo'yash , tahrirlash  imkoniyatlari qo'shildi."
         "2015-yil mart oyining 15-sanasida bo'lgan yangilanishlar  xabar almashishni yanada yaxshilandi , ya'ni xabarlarga"
         " javob qaytarish belgisi va xeshteglar qo'shilgan. Telegram 2015-yil aprel oyida maxfiylikning muhim funksiyasini"
         " ishga tushirdi – Ikki bosqichli tekshirish – yangi qurilmaga kirishda parol talab qilish orqali qo‘shimcha himoya qatlamini qo‘shdi."
         "Foydalanuvchilar fotosuratlarga sarlavha qo'yish imkoniyatiga ega bo'lishdi, shuning uchun kontekst va tarkibni bitta xabar sifatida yuborish mumkin."
         "2015 yil iyun oyida Telegram Bot APIni chiqardi va foydalanuvchilar uchun o'z botlarini yaratish va nashr etish uchun"
         "platforma yaratdi.Botlar Telegramga funksiyalar qo'shish va foydalanuvchi hayotini osonlashtirish uchun mavjud -"
         "botlar to'lovlarni boshqarish , guruhlarni mo'tadil qilish, elektron pochta xabarlarni olish va boshqa ko'p narsalarni"
         "amalga oshirishi mumkin.2015-yil noyabr oyidagi versiyasida kanal va guruhlarga admintrator rolini qo'shilgan,"
         "Administratorlar guruh suhbatlarini boshqarish va qoidalarni bajarish huquqiga ega. Vaqt o'tib, guruh suhbatlari"
         " uchun foydalanuvchilarning maksimal soni superguruhlar qo'shilishi bilan 1000 kishigacha o'sgan."
         "2016-yilning yanvar oyidagi yangilashishlar ,Inline botlar har qanday chatda bot xizmatlaridan foydalanishga imkon beradi,"
         " bu botlarni a'zo sifatida qo'shmasdan - siz shunchaki ularning foydalanuvchi nomi bilan istalgan xabarni boshlaysiz va keyin"
         " kelgan hamma narsa bot uchun so'rovga aylanadi. Ushbu yordamchi dasturlar Vikipediya maqolalarini bog'lashi, YouTube videolarini"
         " joylashtirishi yoki do'stlar bilan ko'ngil ochish uchun GIF-larni qidirishi mumkin. Afsuski, ular juda mohir "
         "bo'lishlariga qaramay, shuncha yillardan keyin ham chana tortolmaydilar."
     "GIF fayl hajmi 95% ga qisqardi, bu esa ularni 20 barobar tezroq yuklash imkonini berdi. Barcha GIF-lar uchun"
         " avtomatik ijro ularning yangi topilgan tezligini ko'rsatish uchun yoqilgan."
         "Superguruh aʼzolari soni 1000 dan 5 000 ga koʻpayganligi sababli tartibni saqlash uchun muhim eʼlonlarni"
         " ekranning yuqori qismida mahkamlangan xabarlar sifatida joylashtirish mumkin edi. Ommaviy superguruhlarda spamning oldini"
         " olishga yordam beradigan qoʻshimcha moderatsiya vositalari joriy etildi. Bunga spam haqida xabar berish, foydalanuvchini "
         "to'g'ridan-to'g'ri taqiqlash yoki guruhdagi barcha postlarini o'chirish mumkin edi."
         "2016-yil mart oyidagi  yangilanishlar ovozli qo'ng'iroqlar sifatini oshirildi, ya'ni tiniq ozov shakliga keltirildi,"
         "video muharririda bo'lgan  o'zgarishlar , video fayli hajmini siqish imkoniyatlari qo'shildi.";
     return text;
  }
  telegram_alternative(){
     String text=
         "Twitter 2006 yilning mart oyida Jek Dorsi, Noah Glass, Biz Stoun va Evan Uilyams tomonidan yaratilgan va shu yilning"
         " iyul oyida ishga tushirilgan. 2012 yilga kelib, 100 milliondan ortiq foydalanuvchiga ega bo'lgan va kuniga o'rtacha"
         " 1,6 milliard qidiruvni tashkil qilgan. 2013-yilda u eng koʻp tashrif buyurilgan saytlar oʻntaligiga kirdi va “Internet SMS-xabarlari” "
         "nomini oldi. 2019 yil boshiga kelib Twitter’ning oylik faol foydalanuvchilari soni 330 milliondan oshdi."
         "2010 yil 14 sentyabr Twitter, Inc. yangilangan logotipni o'z ichiga olgan saytni qayta ishlashni boshladi."
         " 2010-yil 24-sentabrda saytning yangi versiyasi ishga tushirildi, bu foydalanuvchilarga to‘g‘ridan-to‘g‘ri saytda"
         " video va fotosuratlarni ko‘rish imkonini berdi va umuman olganda, foydalanuvchining Twitter bilan o‘zaro aloqasini"
         " boyitib, uni tezroq, oson va funksional qilish imkonini berdi. 2010 yil 4 oktyabrda Evan Uilyams bosh direktor lavozimini"
         " tark etishini e'lon qildi. Uilyamsning stulini kompaniyaning sobiq bosh operatsion direktori Dik Kostolo egalladi. Ammo "
         "Uilyams ishlab chiqarish strategiyasiga to'liq e'tibor qaratish uchun kompaniyada qoldi."
          "2011 yil 26 aprelda Twitter interfeysi turk va rus tillarini qo'llab-quvvatlay boshladi. 2011 yil 3 avgustda kompaniya"
         " vakillari eski interfeysni o'chirib, barcha foydalanuvchilarni bir yil avval ishga tushirilgan yangisiga o'tkazayotganliklarini"
         " e'lon qilishdi. 2011-yil 8-dekabrda Fly Twitter nomi ostida iOS va Android smartfonlari uchun yangi veb va ilovalar interfeysi"
         " ishga tushirildi. Hozirda yopilgan havola mijozni yuklab olishga olib keladi."
    "2012 yilda Twitter, Inc. onlayn reklama tarmog'i xavfsizligini ishlab chiqaruvchi Dasientni sotib oldi. 2012 yil 6 iyunda kompaniyaning yangi logotipi taqdim etildi. "
     "2022-yil 4-mart kuni Roskomnadzor Rossiya Federatsiyasida Twitter’ning bloklanishini e’lon qildi."
   "2022-yil 25-aprelda Twitter direktorlar kengashi Ilon Maskning kompaniyani 44 milliard dollarga sotib olish taklifini qabul qildi.\n"
         "Telegramning yana bir alternative ya'ni muqobil varianti bu Statflo."
         "Statflo nima? Statflo - bu biznesga mijozlar tajribasini yaxshilash va mijozlarning umr bo'yi qiymatini oshirish imkonini beruvchi etakchi mos keluvchi"
          "yakka tartibdagi biznes matnli xabarlar platformasi. Statflo CRM va ma'lumotlar tizimlari bilan muammosiz integratsiyalasha oladi, jo'natiladigan "
         "boy kontentni o'z ichiga oladi va mijozlarga qaragan jamoalarga o'z mijozlari bilan ko'p kanalli xabar almashish imkonini beradi. Mijozlarga qarama-qarshi"
         " bo'lgan jamoalar o'zlarining mijozlar bazasini yagona platforma orqali jalb qilish, saqlab qolish va"
         " ko'paytirish uchun zarur bo'lgan barcha vositalar va kontekstga ega bo'lishi mumkin.\n"
         "Telegramning yana bir muqobili  bu Signal."
         "Signal - bu yuqori darajadagi maxfiylik va foydalanuvchi xavfsizligiga ega mashhur chat ilovasi. Shuningdek, u sizning xabarlaringizni"
         " avtomatik ravishda o'chiradigan taymer bilan birga keladi.Telegramda bo'lgani kabi, siz osongina matnli xabarlar yuborishingiz, "
         "guruh suhbatlarini yaratishingiz, fayllarni almashishingiz va video/ovozli qo'ng'iroqlarni amalga oshirishingiz mumkin."
         " Signal ham foydalanish uchun bepul va reklamasiz.\n"
         "Telegramning eng muqobili bu Whatsapp. Aslida telegramdan oldin yaratilgan,eng qiziq tomoni Whatsappning alternative deyish mumkin."
         "WhatsApp - bu sayyoradagi eng mashhur suhbat dasturlaridan biri. U 1 milliarddan ortiq faol foydalanuvchilarni hisoblaydi"
         " va ovozli qo'ng'iroqlar va video qo'ng'iroqlar kabi kuchli aloqa xususiyatlarini taklif etadi."
     "Agar shaxsiy foydalanish yoki biznes uchun barqaror yechim izlayotgan bo'lsangiz, WhatsApp, albatta, eng yaxshi variantlardan biridir."
         " Biroq, Whatsapp-ning cheklovlaridan biri shundaki, u faqat 4 a'zodan iborat guruh video qo'ng'iroqlarini yaratishga imkon beradi. Agar"
         " siz ko'proq odamlar bilan guruhli qo'ng'iroq qilishni istasangiz, hafsalangiz pir bo'ladi.";
     return text;
  }
  telegram_kanal(){
     String text=
         "Telegram kanali - bu Telegram messenjer vositasi bo'lib, u obunachilarga ma'lumotlarni yetkazish imkonini beradi. Telegram kanallari"
         " 2015-yil sentabr oyida paydo bo‘lgan.Telegram kanallari obuna modelida ishlaydi va blog elementlariga ega yangiliklar tasmasi hisoblanadi."
         " Foydalanuvchi muntazam ravishda ma'lumot olish uchun kanalga obuna bo'ladi. Kanalga yuborilgan xabar obunachilarga muallif nomidan emas,"
         " balki kanal nomidan keladi. Kanalni bir necha kishi, shu jumladan anonim tarzda boshqarishi mumkin."
         "Jamoat kanallarining doimiy nomi, manzili bor va ularni Telegram orqali qidirish orqali topish mumkin."
     "Xususiy kanallarni qidiruv yordamida topib bo'lmaydi, kanalga yaratilgan havola orqali kirish mumkin, uni maxfiylik maqsadida o'zgartirish mumkin."
         "Telegram kanallari blog yuritishning yangi shakliga aylandi, postlarni yetkazish usuli tufayli"
         " shaxsiylashtirilgan – foydalanuvchi borib tasmani aylanib o‘tishi shart emas, u postni xabar sifatida qabul qiladi."
         " Telegramdagi anonim yoki mualliflik bloglari ijtimoiy-siyosiy kun tartibiga ta'sir qilish uchun jiddiy vosita bo'lib, reklama"
         " va pullik kontent odatda an'anaviy ommaviy axborot vositalariga qaraganda qimmatroqdir."
         "Shuningdek, Telegram kanallari ko'pincha media muharrirlari tomonidan o'z obunachilariga kontentni yetkazib berish uchun"
         " alohida kanal sifatida ishlatiladi. Mash yoki Baza kabi ommaviy axborot vositalari dastlab Telegram kanallari bo'lib,"
         " shundan keyingina veb-sayti, ilovasi va boshqa ijtimoiy tarmoqlarda vakili bo'lgan to'liq media resurslariga aylandi."
     "2019-yilda Sankt-Peterburgda sud OAV uchun “Мы можем.ru” Telegram kanalini tan oldi. Kanal muallifiga ko‘ra, bu adliya organi"
     "kanaldagi kontentni nashr qilish uchun javobgarlikni ommaviy axborot vositalarida chop etish mas’uliyatiga o‘xshash tarzda yuklagan birinchi pretsedentdir."
    "Rossiyadagi eng mashhur Telegram kanallarining Medialogy reytingiga ko'ra, eng yaxshi 10 tadan 2 tasi onlayn media hisoblanadi."
         "2021-yil noyabr oyida Telegram rasmiy reklama platformasini ishga tushirdi, shundan so‘ng kanal o‘zining birinchi reklama"
         " kampaniyasini boshladi. Pavlov Durov tomonidan e'lon qilingan shartlarga ko'ra, reklamani ishga tushirish faqat 1 million byudjet"
         " va depozit miqdoridagi belgilangan jadval bilan mumkin, ammo birinchi reklama beruvchilar kriptovalyutalar, kiyim-kechak "
         "savdosi va onlayn haqida eng yaqin kanallar edi.Eng ommabop ijtimoiy tarmoqlarda foydalanuvchiga ko'rsatiladigan barcha nashrlar"
         " foydalanuvchining manfaatlariga avtomatik ravishda moslashtiriladigan yangiliklar tasmasi ko'rinishida ko'rsatiladi, ya'ni u"
         " algoritmlar taklif qilganidek, eng ko'p bo'lgan nashrlarni ko'rsatadi. unga (foydalanuvchi) qiziq. Uni cheksiz aylantirish mumkin."
     "Telegram kanali chat sifatida yaratilgan; agar unda nashr paydo bo'lsa, obunachi xabarnoma oladi. Ikki holatdan tashqari:"
     "Foydalanuvchi ushbu kanaldan bildirishnomalarni vaqtichalik o‘chirib qo‘ygan yoki umuman bildirishnomalarni o‘chirib qo‘ygan."
    "Nashr muallifi “sukut rejim”dan foydalangan.Bu xususiyat bir qator afzallik va kamchiliklarga ega. Masalan, bunday tizimda"
         " ma'lumotlarning qiymati oshadi, chunki foydalanuvchilar past sifatli kontentga ega kanalga obuna bo'lish ehtimoli kamroq."
         "2019-yil 31-may kuni nashr etilgan postlarni muhokama qilish uchun guruhni kanalga ulash mumkin bo‘ldi. Guruh ulangandan"
         " so'ng, obunachilar kanalning pastki qismida 'Muhokama qilish' tugmachasini ko'radilar. Va bundan oldin, 2018 yil 22 dekabrda "
         "guruhlar va kanallarda anonim so'rovlar paydo bo'ldi. 2021-yil 30-dekabrda chiqarilgan versiyadan boshlab Telegram kanallari"
         " va shaxsiy xabarlarda o‘z munosabatini bildirish uchun rasmiy imkoniyat mavjud. Hammasi bo'lib 11 ta mavjud. Shu bilan birga,"
         " kanal muallifi postlarga reaktsiyalarni ham yoqishi, ham o'chirishi mumkin. Shuningdek, foydalanilgan kulgichni muallifning tanlovi bilan cheklash mumkin.";
     return text;
  }
  aktiv_kanallar(){
     String text=
         "Telegramdagi O'zbek kanallari o'rtasida birinchi o'rinda turuvchi Kun.uz saytining telegram kanali hisoblanadi,qachonki 2022-yil hisobiga ko'ra."
         "kun.uz kanali 2015 yilning 20 dekabrda ochilgan. ushbu kanal eng so'ngi yangiliklarni birinchilardan bo'lib habardor bo'lasiz, Kun.uz asosiy "
         "kanali kunlik hisobiga ko'ra 30dan ortiq  postlar joylanadi.kun.uz boshqa faol kanallardan afzalligi shundaki, O'zbekistonda bo'layotgan o'zgrishlarni,yangiliklarni "
         "tezkorlik bilan habar berishidir.\n"
         "Yana bir aktiv kanal bu daryo rasmiy kanalidir. Daryo kanali 2015-yil 28-avgustda ochilgan, bu kanal etibor qaratgan yo'nallishi bu yangiliklardan habardor qilish."
         "Daryo rasmiy kanali foaliyati 2021-yilgacha eng yaxshi darajada edi, 2021-yil davomidagi obunachilar soni 800 mingdan ziyodroq edi, lekin  2022-yilga kelib obunachilar "
         "soni 550 ming obunachiga tushib qoldi.";
     return text;
  }
  telegram_orqali_pul_ishlash(){
     String text=
         "Telegram orqali pul ishlashning yo'llari ko'p va bu oson ish emas.Men ikki yo'li haqida ma'lumot beraman."
         "Telegram kanal orqali pul topish uchun , birinchi navbatda kanal ochishingiz va uni rivojlantirishingiz kerak."
         "Kanal ochish jarayonida kanal nomini yaxshilab o'ylashingiz kerak va keyin nom berishingiz kerak. chunki kanalingiz nomi orqali kanalda qanday ma'lumotlar"
         " borligini bilish mumkin.Telgram foydalanuvchilar ehtiyojalridan kelib chiqgan holda kanal yaratganingiz ma'qul hisoblanadi."
         "Har bir kanalga joylangan postlar foydalanuvchilarni qiziqtirishi va bir biri ulashishi sabab bo'lishi kerak. Tayyorlagan postingiz ostida albatta kanal "
         "manzili bo'lishi kerak.Bu kanalga kiruvchilar uchun qulaylik olib keladi. Deylik kanalingiz rivojlandi va 30 ming yoki 40 ming obunachiga yetganda sizga "
         "reklama masalasi bo'yicha murojaatlar kelib tushadi, albatta siz o'z telegram manziligizni yoki telefon raqamingizni telegram haqida bo'limiga"
         " yozib qo'ygan bo'lsangiz. Reklama chiqarish usuli oddiy, misol kanal obunachisi 30 mingta bo'lsa 30ming so'm belgilashingiz mumkin. Kanal foaligiga va foydalunchilar"
         " ko'pligiga qarab reklama joylash hizmati o'zgarishi mumkin.kanalga post joylashda qilishingiz  mumkin,bo'lmagan ishlar haqida ma'lumot bersam, kanalingizga boshqa bir kanallardan"
         " postlarni nusxalab joylashingiz, bu sizga foydadan ko'ra ziyon keltiradi. kanalingizga eng ko'pi bilan kuniga 3 yoki 4  reklama joylashingiz kerak, aks holda "
         "kanalingizning sifati tushib ketadi va obunachilaringiz kamaya boshlaydi.\n"
         "Botlar orqali pul ishlash , kanal orqali topishdan tubdan farq qiladi.Bot orqali topilgan pullar elektron pul ya'ni Webmoney, Qiwi,Yandex Dengi"
         " kabi elektron hamyonlarga tushurib olinadi.Siz quyidagi 3 xil usul orqali botlardan pul ishlay olasiz."
         "1.Investor botlarga pul tikib pul ishlash,o'z nomi bilan aniqki siz botga pul tikkan holada pul ishlaysiz.Elektron hamyon orqali botga pul ashlaysiz va bot sizga "
         "kunlik 5% yoki undan ko'proq qiymatda pul to'lay boshlaydi.2.Vazifa bajarib pul ishash. Bu ish samarali va xavfsiz hisoblanib, siz reklamada taqdim etilayotgan "
         "kanallarga a'zo bo'lib pul ishlaysiz.kanallarga a'zo bo'lasiz va sizga pul darxol tushirilib beriladi.Tekshirilish bo'limida sizga qancha muddat kanalda a'zo "
         "bo'lgan holatda turishingiz haqida ma'lumot beriladi va shu vaqt ichida kanaldan chiqib ketmasligingiz kerak bo'ladi. Sizda savol tug'ilishi mumkin,bundan "
         "botga qanday foyda , albatta foydali tomoni bor.Botda sizga a'zo bo'lishingiz kerak bo'lgan kanallar ,adminlari botga pul to'lashadi."
         "3.Kazino botlar , Ushbu botlarda siz toshlarni necha son tushishini tahmin qilib pul tikasiz.Toshlar GIF suratlar orqli berib boriladi.Bot siz uchun dastlab "
         "1 dollar qiymatidagi bonus beradi.Siz botda kazino o'yinlaridan pul yutib olaganingizdan so'ng, siz u elektron pullarni hamyonlar Webmoney,Qiwi,Yandex Dengi,Perfect Money,Bitcoin "
         "orqali o'tkazib olishingiz mumkin.";
     return text;
  }
  telegram_bot(){
     String text=
         "Hozirgi kunda telegram tarmog'ida tezlik bilan rivojlanayotgan va foydalanuvchilarga qulaylik yaratyotgan telegram bot yo'nallishi."
         "Aslida bot nima va qanday maqsadlarda foydalaniladi.Ushbu savollar uchun yetarlicha malumot beramiz."
         "Statistikaga qaraganda telegramning hamma foydalnuvchilariga nisbatan telegram botlar ko'p ekan.bot nima? "
         "Maxsus API yordamida uchinchi tomon ishlab chiquvchilari 'botlar', dasturlar tomonidan boshqariladigan maxsus hisoblarni yaratishi mumkin. Odatiy botlar"
         " shaxsiy va guruh chatlarida ma'lum buyruqlarga javob beradi, ular shuningdek, Internetda qidirishlari yoki boshqa vazifalarni bajarishlari mumkin, o'yin-kulgi"
         " yoki biznes maqsadlarida foydalaniladi.Telegram bot yangiliklarini birb boruvchi rasmiy kanal @botnews. ushbu kanal 2017-yilda faoliyatini boshlagan, kanalda "
         "rasmiy habarlar joylanadi."
         "2015 yil sentyabr oyida Pavel Durov botlarda monetizatsiya va reklama qilish imkoniyatlari yaqinda paydo bo'lishini e'lon qildi."
    "2017-yilning 18-mayida botlar uchun to‘lov API’si joriy etildi. Foydalanuvchilar ushbu funksiyani sinab ko‘rishlari uchun Telegram jamoasi Time Machine sotib olishni taklif"
         " qiluvchi test bot yaratdi (foydalanuvchilardan pul undirilmadi).2016-yilning noyabr oyida messenjer uchun botlarni yaratish bo‘yicha botpriz tanlovining birinchi"
         " natijalari sarhisob qilindi. Ishlab chiquvchilar jami 200 000 dollar olishdi.2019-yil mart oyida Ijtimoiy tarmoqlar va messenjerlarning Professional foydalanuvchilari"
         " assotsiatsiyasi (APPSIM) Pavel Durovni ishlab chiquvchilarga 800 ming dollar to‘lamaganlikda aybladi.";
     return text;
  }
   mukammal_bot_yaratish(){
     String text=
         "Mukammal bot yaratish uchun quyidagich ketma ketlikda ma'lumot berib boraman. 1. telegramning qidiruv tizimidan BotFather(@botfather) izlab,unga kiramiz."
         "xabar yozish joyidan buruqlar bo'limiga o'tamiz, '/' buyrug'ini bosing va '/newbot'ni tanlaymiz,keyin sizga bot nomini kiriting degan xabar keladi,ixtiyoriy nom kiriting va"
         " kiritgan nomdan so'ng bot sozini qo'shib qo'ying, chunki bot yaratish qoidasi shunday.2.Telegram bosh sahifasiga o'tib qidiruv tizimidan Manybot(@manybot) ni izlab , unga kiring"
         " boshqaruv bo'limidan CREATE A NEW BOT ni tanlaymiz, so'ng sizga botfather dan yaratgan botingizni API kodni so'raydi.Siz botfatherga kirasiz,boshqaruv bo'limidan mening botlarim"
         " tugmasi bosib, botingizni tanlaysiz va token degan qismidan API kodini nusxalab olasiz,keyin manybot ga qaytib nusxalab olgan kodingizni joylaysiz,Siz skip(o'tkazib yuborish) degan"
         " tugmani tanlaysiz va botingiz tayyor.Telegram bosh sahifasiga o'tib qidiruv tizimidan Botingizni nomini yozasiz , so'ng botingizga kirib, boshqaruv bo'limidan CUSTOM COMMANDS ni tanlysiz"
         " Create Command tugmasi chiqadi, shuni tanlaysiz, endi botingizni boshqarish uchun umumiy bo'lgan so'z kiritasiz, masalan : /rasmlar  , nom berganingizdan so'ng sizga fayl yuborishingiz"
         "haqida xabar keladi, ixtiyoriy bo'lgan  fayllarni joylaysiz,so'ng save(saqlash) tugmasini tanlaysiz,boshqaruv buyruqlari yaratildi, botni boshqaruv bo'limidan +ADD MENU ITEM tugmasini "
         "tanlaysiz,keyin oldinroq yaratilgan boshqaruv buyruqlari asosiy bo'limda qanday nomda ko'rinishi haqida habar keladi , so'ng ixtiyoriy nom kiritasiz va Manybotda qilingan mukammal bot tayyor"
         " Endi sizning botingizda bir boshqaruv tugmasi mavjud, Siz ixtiyoriy tarzda boshqaruv "
         " tugmalarini yaratishingiz mumkin." ;
     return text;
   }
   telegram_email_bot(){
     String text=
         "Turli xil internet saytlarida ro'yxatdan o'tish uchun haqiqiy  e-mail pochta manzilingizni kiritishdan va pochtangizga spamli xabarlar kelishi joningizga tegdimi?\n"
         "Endi tezkor qulay va bepul pochta sizning Telegram messenjeringizda!. Bu sizga taqdim etayotgan botimiz emailni telegramdan ochishingiz va shu yerdan turib habarlarni yuborishingiz"
         " va qabul qilishingiz imkonini beradi. Telegram qidiruv tizimidan Telegram Email(@etlgr_bot) izlang va unga kiring , keyin boshqaruv bo'limidan /start  buyrug'ini bosasiz, so'ng /register ni bosasiz."
         "Bot emailga nom berish haqida habar keladi,ixtiyoriy nom berasiz , so'ng tasdiqlangani haqida xabar keladi va Email pochta tayyor.Kimgadir xabar yozmoqchi bo'lsangiz, /send buyrug'idan"
         " foydalaning.";
     return text;
   }
   guggy_va_guggy_stickers_bot(){
     String text=
         "Guggy botning vazifasi siz yozgan har qanday yozuvni gif formatidagi yana animatsiya suratga siz yozgan yozuvni kiritib ,qayta tahrirlab sizga taqdim etadi.Siz uni do'stlar bilan baham "
         "ko'rishingiz va xotiraga yuklab olishingiz mumkin.Telegram qidiruv tizimidan Guggy(@guggybot) orqali topishingiz mumkin.\n"
         "Guggy sticker bot ham oldingi botga o'xshash va albatta ikkala bot ham bir inson tomonidan yaratilgan.Bu bot orqali yozgan yozuvingizni sizga stiker ko'rinishida qayta yuboradi.Agar"
         " yozgan yozuchingizga stiker to'g'ri kelmasa sizga taqdim etilgan sticker pastidagi chap tomondagi aylana smaylni bosgan xolda boshqasini tanlash imkoniga egasiz.Ushbu botni Telegram qidiruv"
         "tizimidan Guggy stickers bot orqali topishingiz mumkin.";
     return text;
   }
  dastur_haqida(){
     String text="Dastur telegram ijtimoiy tarmog`ida faol bo'lish maqsadida yaratilgan."
         "Dasturdagi ma`lumotlardan ijtimoiy maqsadlarda foydalanilganda, Dastlabki manbasi bilan ko'rsatilisin."
         "Dasturning keyingi versiyalarida yangi ma`lumotlarida qo'shilishi taminlanadi."
         "Ushbu dasturni rivojlantirish yoki hamkorlik qilish va boshqa masalalarda mening telegramdagi sahifamga muroja`at qilishingiz mumkin.";
     return text;
  }
  boglanish(){
     String text="Bo'lanish uchun internet tarmog'iga ulangan bo'lishingiz kerak."
         "Internet tarmog'ida bo'lsangiz bo'lanish tugmasini bosing. Aks holda chiqish tugmasini bosing.";
     return text;
  }
}